Coronitor/Models/TwitterPost.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Coronitor.Models
{
    public class TwitterPost
    {
        public int Id { get; set; }
        [Display(Name = "Post ID")]
        public string PostID { get; set; }
        [Display(Name = "Sick Patient")]
        public User InfectedUser { get; set; }

        [Display(Name = "Post Upload Date")]
        public DateTime PostUploadTime { get; set; }
    }
}

Coronitor/Controllers/TwitterPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Coronitor.Data;
using Coronitor.Models;
using Tweetinvi;
using Tweetinvi.Models;
using Tweetinvi.Parameters;

namespace Coronitor.Controllers
{
    public class TwitterPostsController : Controller
    {
        private static readonly string CONSUMER_KEY = "kAuwNCvr59W2AHAYvIPtLTHdH";
        private static readonly string CONSUMER_SECRET = "OmVkVrVxf7ckpYTQxhU7KcDxe8EvOV1qFEtvSv0vOFyH6qRbKm";
        private static readonly string USER_ACCESS_TOKEN = "1274249583246393344-ujKqSIXMLFyTklgNsxio1N2N5QxZN1";
        private static readonly string USER_ACCESS_SECRET = "cfyItF3b7JaoOXWG73zD9YrPDZrJwrqYHKabC4MMCMGlj";
        private readonly CoronitorContext _context;

        public TwitterPostsController(CoronitorContext context)
        {
            _context = context;
            // set the configuration for the twitter api connection
            if(Auth.ApplicationCredentials == null)
            {
                Auth.SetUserCredentials
                (CONSUMER_KEY, CONSUMER_SECRET, USER_ACCESS_TOKEN, USER_ACCESS_SECRET);
            }
        }

        public async Task NewUserInfectedPost(Models.User user)
        {
            //int a = 
            // Check if we have a post about this user
            if (_context.TwitterPost.Count(x => x.InfectedUser.Id == user.Id) == 0)
            {
                await InformAboutNewInfectionInCityAsync(user);
            }
        }
        public async Task InformAboutNewInfectionInCityAsync(Models.User user)
        {
            City city = user.City;

            // Get city Coordinates
            Coordinates cityLoc = new Coordinates(city.Latitude, city.Longitude);

            // Load twit image
            byte[] twitImage = System.IO.File.ReadAllBytes("wwwroot/images/newCaseImage.jpg");
            var media = Upload.UploadBinary(twitImage);


            string tweetMsg = "התגלה חולה קורונה חדש בעיר - " + city.Name;
            var tweet = Tweet.PublishTweet(tweetMsg,
                new PublishTweetOptionalParameters
                {
                    Coordinates = cityLoc,
                    Medias = new List<IMedia> { media }
                });

           
            _context.TwitterPost.Add(new TwitterPost
            {
                InfectedUser = user,
                PostID = tweet.IdStr,
                PostUploadTime = DateTime.Now
            });

            await _context.SaveChangesAsync();
        }

        public void DeleteTwitterPost(string postID)
        {
            Tweet.DestroyTweet(long.Parse(postID));
        }
            // GET: TwitterPosts
        public async Task<IActionResult> Index(string firstName, string lastName, DateTime postDate)
        {
            if (AccountController.IsAdminUserConnected(this))
            {
                firstName = (firstName == null ? "" : firstName);
                lastName = (lastName == null ? "" : lastName);

                var twitterPosts =
                    _context.TwitterPost.Include(post => post.InfectedUser).Where(s => s.InfectedUser.FirstName.Contains(firstName) &&
                    s.InfectedUser.LastName.Contains(lastName) && s.PostUploadTime >= postDate);

                return View(await twitterPosts.ToListAsync());
            }
            else
            {
                return View("~/Views/Shared/401Error.cshtml");
            }
           
        }

        // GET: TwitterPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (AccountController.IsAdminUserConnected(this))
            {
                if (id == null)
                {
                    return View("~/Views/Shared/Error.cshtml");
                }

                var twitterPost = await _context.TwitterPost.Include(post => post.InfectedUser)
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (twitterPost == null)
                {
                    return View("~/Views/Shared/Error.cshtml");
                }

                return View(twitterPost);
            }
            else
            {
                return View("~/Views/Shared/401Error.cshtml");
            }
           
        }

        // GET: TwitterPosts/Create
        public IActionResult Create()
        {
            if (AccountController.IsAdminUserConnected(this))
            {
                return View();
            }
            else
            {
                return View("~/Views/Shared/401Error.cshtml");
            }
           
        }

        // POST: TwitterPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PostID")] TwitterPost twitterPost)
        {
            if (AccountController.IsAdminUserConnected(this))
            {
                if (ModelState.IsValid)
                {
                    _context.Add(twitterPost);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View(twitterPost);
            }
            else
            {
                return View("~/Views/Shared/401Error.cshtml");
            }
           
        }

        // GET: TwitterPosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (AccountController.IsAdminUserConnected(this))
            {
                if (id == null)
                {
                    return View("~/Views/Shared/Error.cshtml");
                }

                var twitterPost = await _context.TwitterPost.FindAsync(id);
                if (twitterPost == null)
                {
                    return View("~/Views/Shared/Error.cshtml");
                }
                return View(twitterPost);
            }
            else
            {
                return View("~/Views/Shared/401Error.cshtml");
            }
           
        }

        // POST: TwitterPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PostID")] TwitterPost twitterPost)
        {
            if (AccountController.IsAdminUserConnected(this))
            {
                if (id != twitterPost.Id)
                {
                    return View("~/Views/Shared/Error.cshtml");
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(twitterPost);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!TwitterPostExists(twitterPost.Id))
                        {
                            return View("~/Views/Shared/Error.cshtml");
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(twitterPost);
            }
            else
            {
                return View("~/Views/Shared/401Error.cshtml");
            }
          
        }

        // GET: TwitterPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (AccountController.IsAdminUserConnected(this))
            {
                if (id == null)
                {
                    return View("~/Views/Shared/Error.cshtml");
                }

                var twitterPost = await _context.TwitterPost
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (twitterPost == null)
                {
                    return View("~/Views/Shared/Error.cshtml");
                }

                return View(twitterPost);
            }
            else
            {
                return View("~/Views/Shared/401Error.cshtml");
            }
            
        }

        // POST: TwitterPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (AccountController.IsAdminUserConnected(this))
            {
                var twitterPost = await _context.TwitterPost.FindAsync(id);
                DeleteTwitterPost(twitterPost.PostID);
                _context.TwitterPost.Remove(twitterPost);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View("~/Views/Shared/401Error.cshtml");
            }
            
        }

        private bool TwitterPostExists(int id)
        {
            return _context.TwitterPost.Any(e => e.Id == id);
        }
    }
}

Coronitor/Views/TwitterPosts/Create.cshtml
@model Coronitor.Models.TwitterPost

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TwitterPost</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PostID" class="control-label"></label>
                <input asp-for="PostID" class="form-control" />
                <span asp-validation-for="PostID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Coronitor/Views/TwitterPosts/Delete.cshtml
@model Coronitor.Models.TwitterPost

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TwitterPost</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Coronitor/Views/TwitterPosts/Details.cshtml
@model Coronitor.Models.TwitterPost

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TwitterPost</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PostID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PostID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.InfectedUser.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.InfectedUser.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.InfectedUser.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.InfectedUser.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PostUploadTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PostUploadTime)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Coronitor/Views/TwitterPosts/Edit.cshtml
@model Coronitor.Models.TwitterPost

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TwitterPost</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PostID" class="control-label"></label>
                <input asp-for="PostID" class="form-control" />
                <span asp-validation-for="PostID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Coronitor/Views/TwitterPosts/Index.cshtml
@model IEnumerable<Coronitor.Models.TwitterPost>

@{
    ViewData["Title"] = "Twitter Posts";
}
<link rel="stylesheet" href="~/css/TwitterPostStyle.css">

<form asp-controller="TwitterPosts" asp-action="Index">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputEmail4">First Name:</label>
            <input type="text" name="firstName" class="form-control" placeholder="First name" aria-label="Recipient's username" aria-describedby="basic-addon2">
        </div>
        <div class="form-group col-md-6">
            <label for="inputPassword4">Last Name:</label>
            <input type="text" name="lastName" class="form-control" placeholder="Last name" aria-label="Recipient's username" aria-describedby="basic-addon2">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputEmail4">Posted before:</label>
            <input type="date" name="postDate" class="form-control" placeholder="Posted before" aria-label="Recipient's username" aria-describedby="basic-addon2">
        </div>
        <div class="form-group col-md-6">
            <label for="inputEmail4">Search:</label>
            <input value="search" type="submit" name="postDate" class="btn btn-outline-secondary form-control" placeholder="Posted before" aria-label="Recipient's username" aria-describedby="basic-addon2">
        </div>
    </div>
</form>
@if (@Model.Count() == 0)
{
    <div class="alert alert-dark" role="alert">
        sorry, there is no such twitter post
    </div>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PostID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.InfectedUser.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.InfectedUser.LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PostUploadTime)
                </th>
                <th>
                    post link
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PostID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.InfectedUser.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.InfectedUser.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PostUploadTime)
                    </td>
                    <td>
                       
                        <a href="https://twitter.com/daudi_batel/status/@item.PostID"> 
                            <img src="https://img.icons8.com/fluent/48/000000/twitter.png" /></a>
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

}