Coronitor/Controllers/EventsController.cs
using Coronitor.Data;
using Coronitor.Migrations;
using Coronitor.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Coronitor.Controllers
{
    public class EventsController : Controller
    {
        private readonly CoronitorContext _context;

        public EventsController(CoronitorContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(Boolean IsSick, DateTime EventDate, int Status = -1)
        {

            var events = GetEruimByPermission().Cast<Event>().Where(e => (Status == -1 || e.Status == (EventStatus)Status) &&
                                                                         (!IsSick || e.IsSick == IsSick) && 
                                                                          e.CreationTime >= EventDate);

            events = Calculate(events);
            return View(await events.ToListAsync());
        }

        private IQueryable<Event> Calculate(IQueryable<Event> events)
        {
            foreach (var item in events)
            {
                // get the symptoms of the current event 
                var symptomsId = _context.EventSymptoms.Where(e => e.EventId == item.Id).Select(e => e.SymptomId);
                // get the events that has at least one symptom of the current event symptoms
                var all = _context.EventSymptoms.Where(es => symptomsId.Contains(es.SymptomId));
                // get the count of the sick people
                var count = all.Where(e => e.Event.IsSick).Select(e => e.EventId).Distinct().Count();
                // calculate chance to be sick
                item.ChanchToBeSick = all.Count() != 0 ? (count * 100) / all.Select(e => e.Event).Distinct().Count() : -1;
            }

            return events;
        }


        private IQueryable GetEruimByPermission()
        {
            var jobid = HttpContext.Session.GetInt32("jobtype");
            var userid = HttpContext.Session.GetInt32("id");
            var query = _context.Event.Include(e => e.Doctor)
                .Include(e => e.Patient)
                .Include(e => e.Symptoms).ThenInclude(es => es.Symptom);

            if (HttpContext.Session.GetString("admin") != null)
            {
                return query;
            }
            else if (jobid == (int)JobTypeEnum.Patient)
            {
                return query.Where(e => e.Patient.Id == userid);
            }
            else if (jobid == (int)JobTypeEnum.Doctor)
            {
                return query.Where(e => e.Doctor.Id == userid);
            }
            else if (jobid == (int)JobTypeEnum.LaboratoryDirector)
            {
                return query;
            }
            return null;
        }

        // get create view
        public IActionResult Create()
        {
            ViewBag.Doctors = new SelectList(_context.User.Where(u => u.JobType.Id == (int)JobTypeEnum.Doctor), "Id", "FullName");
            ViewBag.Symptoms = new SelectList(_context.Symptom.ToList(), "Id", "Name");
            if(!(HttpContext.Session.GetInt32("jobtype") == (int)JobTypeEnum.Patient))
            {
                ViewBag.Patients = new SelectList(_context.User.Where(u => u.JobType.Id == (int)JobTypeEnum.Patient), "Id", "FullName");
            }

            return View();
        }

        // create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Temperature")] Event @event, List<int> Symptoms, int Doctor, int? Patient = null)
        {
            if (ModelState.IsValid)
            {
                int userId = (HttpContext.Session.GetInt32("id").HasValue ? (int)HttpContext.Session.GetInt32("id") : 123456789);
                @event.CreationTime = DateTime.Now;
                @event.UpdateTime = DateTime.Now;
                @event.Status = EventStatus.New;
                @event.Patient = Patient.HasValue 
                    ? _context.User.Where(u => u.Id == Patient).FirstOrDefault()
                    : _context.User.Where(u => u.Id == userId).FirstOrDefault();
                @event.Doctor = _context.User.Where(u => u.Id == Doctor).FirstOrDefault();
                var e =_context.Add(@event);
                _context.SaveChanges();
                foreach (var symptom in Symptoms)
                {
                    var es = new EventSymptom() { SymptomId = symptom, EventId = e.Entity.Id };
                    _context.Add(es);
                }
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // get edit view
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("~/Views/Shared/Error.cshtml");
            }

            var @event = await GetEruimByPermission().Cast<Event>()
                .FirstOrDefaultAsync(x => x.Id == id);
            
            if (@event == null)
            {
                return View("~/Views/Shared/Error.cshtml");
            }

            var model = new EditEventViewModel
            {
                Id = @event.Id,
                Patient = @event.Patient,
                IsSick = @event.IsSick,
                DoctorId = @event.Doctor.Id,
                Status = @event.Status,
                SymptomsIds = @event.Symptoms.Select(s => s.SymptomId).ToArray(),
                Temperature = @event.Temperature,
                TestDate = @event.TestDate
            };

            var doctorsLst = new List<SelectListItem>();
            var statusesLst = new List<SelectListItem>();
            var symptomsLst = new List<SelectListItem>();
            var doctors = _context.User.Where(u => u.JobType.Id == (int)JobTypeEnum.Doctor).ToList();
            var statuses = Enum.GetValues(typeof(EventStatus)).Cast<EventStatus>();
            var symptoms = _context.Symptom.ToList();

            foreach (var doctor in doctors)
            {
                doctorsLst.Add(new SelectListItem
                {
                    Text = doctor.FullName,
                    Value = doctor.Id.ToString(),
                });
            }

            foreach (var status in statuses)
            {
                statusesLst.Add(new SelectListItem
                {
                    Text = Enum.GetName(typeof(EventStatus), status),
                    Value = status.ToString(),
                });
            }

            foreach (var symptom in symptoms)
            {
                symptomsLst.Add(new SelectListItem
                {
                    Text = symptom.Name,
                    Value = symptom.Id.ToString(),
                });
            }

            model.DoctorsLst = doctorsLst;
            model.StatusesLst = statusesLst;
            model.SymptomsLst = symptomsLst;

            return View(model);
        }


        // edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, IsSick, Status, TestDate, Temperature", "DoctorId", "StatusId", "Patient")] EditEventViewModel @event, List<int> SymptomsIds)
        {
            if (id != @event.Id)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
            if(!(GetEruimByPermission().Cast<Event>().Any(e => e.Id == id)))
            {
                return View("~/Views/Shared/Error.cshtml");
            }
            // check if the user is sick
            else if(@event.IsSick)
            {
                var eventPatient = await _context.Event
                   .Include(u => u.Patient).ThenInclude(user=> user.City).FirstOrDefaultAsync(m => m.Id == id);

                _context.Entry(eventPatient).State = EntityState.Detached;
                _context.SaveChanges();
          
                await (new TwitterPostsController(_context)).NewUserInfectedPost(eventPatient.Patient);

            }

            if (ModelState.IsValid)
            {
                try
                {
                    Event newevent = new Event
                    {
                        Id = @event.Id,
                        Temperature = @event.Temperature,
                        IsSick = @event.IsSick,
                        TestDate = @event.TestDate,
                        UpdateTime = DateTime.Now,
                        Status = @event.Status,
                        Doctor = _context.User.FirstOrDefault(u => u.Id == @event.DoctorId),
                    };

                    _context.RemoveRange(_context.EventSymptoms.Where(es => es.EventId == newevent.Id));
                    foreach (var symptom in SymptomsIds)
                    {
                        var es = new EventSymptom() { SymptomId = symptom, EventId = newevent.Id };
                        _context.Add(es);
                    }
                    _context.SaveChanges();

                    _context.Update(newevent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.Id))
                    {
                        return View("~/Views/Shared/Error.cshtml");
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // get delete view
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return View("~/Views/Shared/Error.cshtml");
            }

Coronitor/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Coronitor.Models;

namespace Coronitor.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

       

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Coronitor/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Coronitor.Models;
using OpenCage.Geocode;

namespace Coronitor.Controllers
{
    public class MapController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public MapController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }


        public IActionResult GoogleMaps()
        {
            return View();
        }
        public IActionResult GetCities()
        {


            List<City> cities = new List<City>(){
        };

            // New thread for posting the twitt
            Task t = Task.Factory.StartNew(() =>
            {
                new TwitterController(_logger).TwwitTwit();

            });
            

            return new JsonResult(cities);

        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Coronitor/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<head>
    <link rel="stylesheet" href="~/css/homeStyle.css">
</head>
<body>
    <header>
        <img class="main-img" src="~/images/corona-4.png" />
    </header>
    <section>
        <div class="header">
            <canvas class="canvas" id="myCanvas" width="240" height="40"></canvas>
        </div>
        <div class="newspapaer">
            Coronavirus disease (COVID-19) is an infectious disease caused by a newly discovered coronavirus.
            Most people infected with the COVID-19 virus will experience mild to moderate respiratory illness and recover without requiring special treatment.  Older people, and those with underlying medical problems like cardiovascular disease, diabetes, chronic respiratory disease, and cancer are more likely to develop serious illness.
            The best way to prevent and slow down transmission is be well informed about the COVID-19 virus, the disease it causes and how it spreads. Protect yourself and others from infection by washing your hands or using an alcohol based rub frequently and not touching your face.
            The COVID-19 virus spreads primarily through droplets of saliva or discharge from the nose when an infected person coughs or sneezes, so it’s important that you also practice respiratory etiquette (for example, by coughing into a flexed elbow).
            At this time, there are no specific vaccines or treatments for COVID-19. However, there are many ongoing clinical trials evaluating potential treatments. WHO will continue to provide updated information as soon as clinical findings become available.
        </div>
    </section>
    <section class="video-section">
        <video class="video" width="540" height="305" controls>
            <source src="~/images/The Coronavirus Explained & What You Should Do.mp4" type="video/mp4" />
            Your browser does not support the video tag.
        </video>
        <img class="video-image" src="~/images/317270_webGraphics4_1000x315_noText_2.jpg" />
    </section>
    <section class="container-crown">
        <div class="text-crown">
            Coronaviruses are composed of genetic material surrounded by a round envelope that has protein spikes on the outside that resemble the spikes on a crown, the metal headgear worn by many monarchs across the world, WHO explained in a video. “Crown” in Latin is “corona,” hence the name coronavirus.
        </div>
        <aside>
            <img class="img-crown" src="~/images/corona-crown.png" />
        </aside>
    </section>
    <footer>
        <nav class="container">
            <div class="img-container" onclick="window.location.assign('@Url.Action("Index","Events")')">
                <img class="img" src="~/images/Corona-test-hero-a219365.jpg" />
                <div class="img-textbox">
                    <div class="img-text">Events</div>
                </div>
            </div>
            <div class="img-container" onclick="window.location.assign('@Url.Action("GoogleMaps","Map")')">
                <img class="img" src="~/images/location.jpg" />
                <div class="img-textbox">
                    <div class="img-text">Map</div>
                </div>
            </div>
            <div class="img-container" onclick="window.location.assign('@Url.Action("Index","Statistics")')">
                <img class="img" src="~/images/oie_21172016kSal4p7v.jpg" />
                <div class="img-textbox">
                    <div class="img-text">Statistics</div>
                </div>
            </div>
        </nav>
    </footer>
    <script>
        var c = document.getElementById("myCanvas");
        var ctx = c.getContext("2d");
        ctx.font = "28px Roboto";
        ctx.textAlign = "center";
        ctx.fillText("About Coronavirus", c.width/2, c.height/2);
    </script>
</body>