Coronitor/Models/City.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace Coronitor.Models
{
    public class City
    {
        public City()
        {
           
        }
  
        [Display(Name = "City Name")]
        public string Name { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public string Id { get; set; }
    }
}

Coronitor/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Coronitor.Data;
using Coronitor.Models;
using OpenCage.Geocode;
using System.Text.Json;
using System.Data;
using Microsoft.AspNetCore.Http;

namespace Coronitor.Controllers
{
    public class CitiesController : Controller
    {
        private readonly CoronitorContext _context;
        private static int CitySequnce = 0;
        private static string GEO_CODER_API_KEY = "64afde3b45f14dc08cce2e98089f3c70";
        private static int LONG_LAT_DEFAULT_VALUE = 0;

        private async Task<string> GetNextCityIDAsync()
        {
            int maxSequence = 1;
            var cities = await _context.City.ToListAsync();

            foreach (City city in cities)
            {
                if(int.Parse(city.Id) > maxSequence)
                {
                    maxSequence = int.Parse(city.Id);
                }
            }
            maxSequence++;

            return (maxSequence.ToString());
        }

   
    private async Task InsertCitiesName()
        {
            List<string> cities = new List<string>(){
"מודיעין עילית",
"מטולה",
"מעלה אדומים",
"מעלות-תרשיחא",
"נהריה",
"נס ציונה",
"נצרת עילית",
"נשר",
"נתיבות",
"נתניה",
"עכו",
"עפולה",
"ערד",
"פתח תקווה",
"צפת",
"קריית אונו",
"קריית ארבע",
"קריית אתא",
"קריית ביאליק",
"קריית גת",
"קריית ים",
"קריית מוצקין",
"קריית מלאכי",
"קריית שמונה",
"קריית טבעון",
"ראש העין",
"ראש פינה",
"ראשון לציון",
"רחובות",
"רמלה",
"רמת גן",
"רמת השרון",
"רעננה",
"שדרות",
"תל אביב",
"אופקים",
"אור יהודה",
"אור עקיבא",
"אילת",
"אלעד",
"אריאל",
"אשדוד",
"אשקלון",
"באר שבע",
"בית שאן",
"בית שמש",
"ביתר עילית",
"בני ברק",
"בת ים",
"גבעת שמואל",
"גבעתיים",
"דימונה",
"הוד השרון",
"הרצליה",
"זכרון יעקב",
"חדרה",
"חולון",
"חיפה",
"טבריה",
"טירת כרמל",
"יבנה",
"יהוד-מונוסון",
"יפו",
"יקנעם",
"ירושלים",
"כפר סבא",
"כרמיאל",
"לוד",
"מגדל העמק",
"מודיעין-מכבים-רעות" };
            cities.ForEach(async city =>
            {
                _context.Add(new City
                {
                    Name = city,
                    Id = await GetNextCityIDAsync(),
                    Longitude = LONG_LAT_DEFAULT_VALUE,
                    Latitude = LONG_LAT_DEFAULT_VALUE,
                });
                CitySequnce++;
            });

            // Save changes to DB
            _context.SaveChanges();
        }

        public CitiesController(CoronitorContext context)
        {
            _context = context;
        }

        // GET: Cities
        public async Task<IActionResult> Index(string cityName)
        {

            if (AccountController.IsAdminUserConnected(this))
            {
                cityName = (cityName == null ? "" : cityName);

                if (_context.City.Count() < 1)
                    await InsertCitiesName();

                await LoadCitiesLocationAsync();


                var cities =
                    _context.City.Where(city => city.Name.Contains(cityName));

                return View(await cities.ToListAsync());
            }
            else
            {
                return View("~/Views/Shared/401Error.cshtml");
            }
          
        }
        private async Task LoadCitiesLocationAsync()
        {
           
            // Gets all the cities that we dont have locations for
            var cities = await _context.City.Where(s => s.Longitude == LONG_LAT_DEFAULT_VALUE &&
                                                s.Latitude == LONG_LAT_DEFAULT_VALUE).ToListAsync();
            
            cities.ForEach(city => LoadCityCordinates(city));

            _context.SaveChanges();
        }

        private bool LoadCityCordinates(City city)
        {

            bool isLoadingWasSuccsuscel = false;

            Geocoder gc = new Geocoder(GEO_CODER_API_KEY);

            var citySearchResult = gc.Geocode(city.Name);

            // Checks if we got result for this city
            if (citySearchResult != null && 
                citySearchResult.Results.Length > 0 &&
                citySearchResult.Results[0].Components.CountryCode == "il")
            {
                city.Latitude = citySearchResult.Results[0].Geometry.Latitude;
                city.Longitude = citySearchResult.Results[0].Geometry.Longitude;
                isLoadingWasSuccsuscel = true;
            }

            return (isLoadingWasSuccsuscel);
        }
        // GET: Cities/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (AccountController.IsAdminUserConnected(this))
            {
                if (id == null)
                {
                    return View("~/Views/Shared/Error.cshtml");
                }

                var city = await _context.City
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (city == null)
                {
                    return View("~/Views/Shared/Error.cshtml");
                }

                return View(city);
            }
            else
            {
                return View("~/Views/Shared/401Error.cshtml");
            }
          
        }

        public async Task<IActionResult> GetNumberOfSickPeopleInEveryCity()
        {
            if (AccountController.IsAdminUserConnected(this))
            {
                // Get all sick events
                var eventPatientCities = await _context.Event.Include(x => x.Patient)
                    .ThenInclude(p => p.City).Where(e => e.IsSick).ToListAsync();

                // Get all cities
                var cities = await _context.City.ToListAsync();

                Dictionary<string, int> map = new Dictionary<string, int>();

                // Map the number of infections in every city
                foreach (var cityInfection in
                   eventPatientCities.GroupBy(e => e.Patient.City.Id)
                   .Select(g => new { cityID = g.Key, count = g.Count() }))
                {
                    map[cityInfection.cityID] = cityInfection.count;
                }

                List<Object> citiesAndInfections = new List<Object>();

                // Create the respond to the map view
                foreach (var city in cities)
                {
                    int numOfInfections = 0;

                    if (map.ContainsKey(city.Id))
                    {
                        numOfInfections = map[city.Id];
                    }

                    citiesAndInfections.Add(new
                    {
                        city.Name,
                        numOfInfections = numOfInfections,
                        city.Longitude,
                        city.Latitude
                    });

                }

                return new JsonResult(citiesAndInfections);
            }
            else
            {
                return View("~/Views/Shared/401Error.cshtml");
            }
          
        }

        // GET: Cities/Create
        public IActionResult Create()
        {
            if (AccountController.IsAdminUserConnected(this))
            {
                ViewBag.loadingFailed = false;
                ViewBag.cityAlredyExist = false;


                return View();
            }
            else
            {
                return View("~/Views/Shared/401Error.cshtml");
            }
           
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,InfectedNum")] City city)
        {
            if (AccountController.IsAdminUserConnected(this))
            {
                ViewBag.loadingFailed = false;
                ViewBag.cityAlredyExist = false;

                if (ModelState.IsValid)
                {
                    if (_context.City.Where(currCity => currCity.Name == city.Name).ToListAsync().Result.Count >= 1)
                    {
                        ViewBag.cityAlredyExist = true;
                        return View();
                    }
                    else
                    {
                        city.Id = await GetNextCityIDAsync();
                        if (LoadCityCordinates(city))
                        {
                            _context.Add(city);
                            await _context.SaveChangesAsync();
                            return View(city);
                        }

                        ViewBag.loadingFailed = true;
                    }
                }

                return View();
            } else
            {
                return View("~/Views/Shared/401Error.cshtml");
            }

        }

        // GET: Cities/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (AccountController.IsAdminUserConnected(this)) { 
                if (id == null)
                {
                    return View("~/Views/Shared/Error.cshtml");

                }

            var city = await _context.City.FindAsync(id);
            if (city == null)
            {
                return View("~/Views/Shared/Error.cshtml");

            }
            return View(city);
            } else {
                return View("~/Views/Shared/401Error.cshtml");
            }
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Name,Longitude,Latitude,Id,InfectedNum")] City city)
        {

Coronitor/Views/Cities/CitytNotFound.cshtml
@{
    ViewData["Title"] = "CitytNotFound";
}

<h1>CitytNotFound</h1>

Coronitor/Views/Cities/Create.cshtml
@model Coronitor.Models.City
<h1>Add City</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@if (Model != null && Model.Latitude != null)
{
    <div class="alert alert-primary" role="alert">
        The city @Model.Name was added !
    </div>

}
else if (ViewBag.cityAlredyExist)
{
    <div class="alert alert-warning" role="alert">
        The city already exists, Try another one
    </div>
}
else if (ViewBag.loadingFailed)
{
<div class="alert alert-danger" role="alert">
    No such city, try again
</div>
}

<div>
    <a asp-action="Index">Back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Coronitor/Views/Cities/Delete.cshtml
@model Coronitor.Models.City

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>City</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
    </dl>

    <form asp-action="Delete">
        @if (!(bool)ViewData["cityDeletedFailed" + @Model.Id])
        {<input type="submit" value="Delete" class="btn btn-danger" /> }
        else
        {
    <div class="alert alert-danger" role="alert">
        can't delete this city - maybe the city is being used by other model
    </div>
        }
        <input type="hidden" asp-for="Id" />

        | <a asp-action="Index">Back to List</a>
    </form>    
   
    
</div>

Coronitor/Views/Cities/Details.cshtml
@model Coronitor.Models.City

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>City</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Coronitor/Views/Cities/Edit.cshtml
@model Coronitor.Models.City

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>City</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Coronitor/Views/Cities/Index.cshtml
@model IEnumerable<Coronitor.Models.City>
<div class="input-group-append" style="margin-bottom: 20px;">
    <a class="btn btn-primary input-group-append" asp-action="Create" role="button">Add New City</a>
</div>

<form asp-controller="Cities" asp-action="Index">
    <div class="input-group mb-3">
        <input type="text" name="cityName" class="form-control" placeholder="City Name" aria-label="Recipient's username" aria-describedby="basic-addon2">
        <div class="input-group-append">
            <input class="btn btn-outline-secondary" type="submit" value="Filter">
        </div>
    </div>
</form>

@if (@Model.Count() == 0)
{
    <div class="alert alert-dark" role="alert">
        sorry, there is no such cities
    </div>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Longitude)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Latitude)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Longitude)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Latitude)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}